const cardsData = [
  // "Seguridad Privada",
  {
    id: 1,
    title: "Máster Univesitario",
    description: "Seguridad Privada",
    img: "assets/images/cards/pdf1.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Amenazas Híbridas, Seguridad y Defensa
  {
    id: 2,
    title: "Máster Univesitario",
    description: "Amenazas Híbridas, Seguridad y Defensa",
    img: "assets/images/cards/pdf2.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Geoestrategia Internacional y Terrorismo Yihadista
  {
    id: 3,
    title: "Máster Univesitario",
    description: "Geoestrategia Internacional y Terrorismo Yihadista",
    img: "assets/images/cards/pdf3.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Historia Militar
  {
    id: 4,
    title: "Máster Univesitario",
    description: "Historia Militar",
    img: "assets/images/cards/pdf4.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Ciberseguridad, Análisis e Ingeniería
  {
    id: 5,
    title: "Máster Univesitario",
    description: "Ciberseguridad, Análisis e Ingeniería",
    img: "assets/images/cards/pdf5.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Ciberseguridad, Ciberterrorismo y Ciberguerra
  {
    id: 6,
    title: "Máster Univesitario",
    description: "Ciberseguridad, Ciberterrorismo y Ciberguerra",
    img: "assets/images/cards/pdf6.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Dirección y Gestión de la Ciberseguridad
  {
    id: 7,
    title: "Máster Univesitario",
    description: "Dirección y Gestión de la Ciberseguridad",
    img: "assets/images/cards/pdf7.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // "Compliance Penal y Tecnológico",
  {
    id: 8,
    title: "Máster",
    description: "Compliance Penal y Tecnológico",
    img: "assets/images/cards/pdf8.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 6000,
    priceNow: 2200,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "60 ETC",
    modalidad: "Online",
  },
  // "Derecho Internacional Humanitario y su Aplicación Práctica ante Conflictos",
  {
    id: 9,
    title: "Máster Oficial",
    description: "Derecho Internacional Humanitario y su Aplicación Práctica ante Conflictos",
    img: "assets/images/cards/pdf9.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "4 meses",
    creditos: "60 ETC",
    modalidad: "Online",
  },
  // Diplomacia, Relaciones Internacionales, Seguridad y Defensa (DRISYD)
  {
    id: 10,
    title: "Máster Univesitario",
    description: "Diplomacia, Relaciones Internacionales, Seguridad y Defensa (DRISYD)",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // "Criminalística Forense
  {
    id: 11,
    title: "Máster Univesitario",
    description: "Criminalística Forense",
    img: "assets/images/cards/pdf11.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Criminología y Victimología",
  {
    id: 12,
    title: "Máster Univesitario",
    description: "Criminología y Victimología",
    img: "assets/images/cards/pdf12.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Neurocriminología y Psicopatología Criminal
  {
    id: 13,
    title: "Máster Univesitario",
    description: "Neurocriminología y Psicopatología Criminal",
    img: "assets/images/cards/pdf13.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 8000,
    priceNow: 4500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "10 meses",
    creditos: "50 ETC",
    modalidad: "Online",
  },
  // Inteligencia
  {
    id: 14,
    title: "Máster Univesitario",
    description: "Inteligencia",
    img: "assets/images/cards/pdf14.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 8000,
    priceNow: 4500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "10 meses",
    creditos: "50 ETC",
    modalidad: "Online",
  },

  // ---- EXECUTIVES ----

  // "Seguridad Privada",
  {
    id: 15,
    title: "Máster Executive",
    description: "Seguridad Privada",
    img: "assets/images/cards/pdf1.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Seguridad Turística y de los Medios de Transporte ## Falta imagen
  {
    id: 16,
    title: "Máster Executive",
    description: "Seguridad Turística y de los Medios de Transporte",
    img: "assets/images/cards/pdf2.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Criminología y Victimología",
  {
    id: 17,
    title: "Máster Executive",
    description: "Criminología y Victimología",
    img: "assets/images/cards/pdf12.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Criminología y Victimología",
  {
    id: 18,
    title: "Máster Executive",
    description: "Criminología y Victimología",
    img: "assets/images/cards/pdf12.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Neurocriminología y Psicopatología Criminal
  {
    id: 19,
    title: "Máster Executive",
    description: "Neurocriminología y Psicopatología Criminal",
    img: "assets/images/cards/pdf13.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 8000,
    priceNow: 4500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "10 meses",
    creditos: "50 ETC",
    modalidad: "Online",
  },
  // Ciberseguridad, Análisis e Ingeniería
  {
    id: 20,
    title: "Máster Executive",
    description: "Ciberseguridad, Análisis e Ingeniería",
    img: "assets/images/cards/pdf5.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Ciberseguridad, Ciberterrorismo y Ciberguerra
  {
    id: 21,
    title: "Máster Executive",
    description: "Ciberseguridad, Ciberterrorismo y Ciberguerra",
    img: "assets/images/cards/pdf6.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Dirección y Gestión de la Ciberseguridad
  {
    id: 22,
    title: "Máster Executive",
    description: "Dirección y Gestión de la Ciberseguridad",
    img: "assets/images/cards/pdf7.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Inteligencia
  {
    id: 23,
    title: "Máster Executive",
    description: "Inteligencia",
    img: "assets/images/cards/pdf14.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 8000,
    priceNow: 4500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "10 meses",
    creditos: "50 ETC",
    modalidad: "Online",
  },
  // Amenazas Híbridas, Seguridad y Defensa
  {
    id: 24,
    title: "Máster Executive",
    description: "Amenazas Híbridas, Seguridad y Defensa",
    img: "assets/images/cards/pdf2.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Geoestrategia Internacional y Terrorismo Yihadista
  {
    id: 25,
    title: "Máster Executive",
    description: "Geoestrategia Internacional y Terrorismo Yihadista",
    img: "assets/images/cards/pdf3.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Historia Militar
  {
    id: 26,
    title: "Máster Executive",
    description: "Historia Militar",
    img: "assets/images/cards/pdf4.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // Historia Militar
  {
    id: 27,
    title: "Máster Executive",
    description: "Conflictos Armados Contemporáneos",
    img: "assets/images/cards/pdf4.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online",
  },
  // "Compliance Penal y Tecnológico",
  {
    id: 28,
    title: "Máster Executive",
    description: "Compliance Penal y Tecnológico",
    img: "assets/images/cards/pdf8.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 6000,
    priceNow: 2200,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "60 ETC",
    modalidad: "Online",
  },
  // "Derecho Internacional Humanitario y su Aplicación Práctica ante Conflictos",
  {
    id: 29,
    title: "Máster Executive",
    description: "Derecho Internacional Humanitario y su Aplicación Práctica ante Conflictos",
    img: "assets/images/cards/pdf9.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "4 meses",
    creditos: "60 ETC",
    modalidad: "Online",
  },
  // Diplomacia, Relaciones Internacionales, Seguridad y Defensa (DRISYD)
  {
    id: 30,
    title: "Máster Executive",
    description: "Diplomacia, Relaciones Internacionales, Seguridad y Defensa (DRISYD)",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },

  // CURSOS EXPERTOS Y DIPLOMADOS
  // Curso de Gestión de la Seguridad en Puertos
  {
    id: 31,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Curso de Gestión de la Seguridad en Puertos",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Curso Superior de Director de Seguridad
  {
    id: 32,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Curso Superior de Director de Seguridad",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Diploma Superior Universitario de Detective Privado
  {
    id: 33,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Diploma Superior Universitario de Detective Privado",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Diplomado en Reconstrucción de Investigación de Accidentes de Tráfico
  {
    id: 34,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Diplomado en Reconstrucción de Investigación de Accidentes de Tráfico",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Perito Judicial en Seguridad Privada
  {
    id: 35,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Perito Judicial en Seguridad Privada",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Curso de Gestión de la Seguridad Aeroportuaria
  {
    id: 36,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Curso de Gestión de la Seguridad Aeroportuaria",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Curso de Gestión de la Seguridad en Infraestructuras Hoteleras
  {
    id: 37,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Curso de Gestión de la Seguridad en Infraestructuras Hoteleras",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Delincuencia Organizada y Trata de Seres Humanos
  {
    id: 38,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Delincuencia Organizada y Trata de Seres Humanos",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Ciberespacio y Relaciones Internacionales
  {
    id: 39,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Ciberespacio y Relaciones Internacionales",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Derecho Internacional en el Ciberespacio
  {
    id: 40,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Derecho Internacional en el Ciberespacio",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // El Agresor, la Víctima y los Aspectos Legales
  {
    id: 41,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "El Agresor, la Víctima y los Aspectos Legales",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Intervención con Delincuentes Menores y Violencia Intrafamiliar
  {
    id: 42,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Intervención con Delincuentes Menores y Violencia Intrafamiliar",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
  // Inteligencia, Psicología y Toma de Decisiones
  {
    id: 43,
    title: "Diplomados Superiores Y Cursos Técnicos",
    description: "Inteligencia, Psicología y Toma de Decisiones",
    img: "assets/images/cards/pdf10.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online",
  },
];

export default cardsData;
