

const cardsData = [
  {
    id: 1, 
    title: 'Máster Oficial', 
    description: 'Derecho Internacional Humanitario y su Aplicación Práctica ante Conflictos',
    img: "../assets/images/cards/pdf1.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "4 meses",
    creditos: "60 ETC",
    modalidad: "Online"
  },
  { 
    id: 2,
    title: 'Máster', 
    description: 'Compliance Penal y Tecnológico',
    img: "../assets/images/cards/pdf2.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 6000,
    priceNow: 2200,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "60 ETC",
    modalidad: "Online"
  },
  { 
    id: 3,
    title: 'Máster Univesitario', 
    description: 'Amenazas Híbridas Seguridad y Defensa',
    img: "../assets/images/cards/pdf3.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 8000,
    priceNow: 4500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "10 meses",
    creditos: "50 ETC",
    modalidad: "Online"
  },
  { 
    id: 4,
    title: 'Máster Univesitario', 
    description: 'Criminología y Victimología',
    img: "../assets/images/cards/pdf4.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 175,
    priceNow: 100,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "5 a 8 meses",
    creditos: "30 ETC",
    modalidad: "Online"
  },
  { 
    id: 5,
    title: 'Máster Univesitario', 
    description: 'Criminalística Forense',
    img: "../assets/images/cards/pdf5.png",
    titleMobile: "Título por Universidad eCampos",
    imgInstitution: "assets/images/ecampus.png",
    institution: "eCampus",
    priceBefore: 5000,
    priceNow: 2500,
    icon1: "assets/icons/CLOCK_icon.svg",
    icon2: "assets/icons/BOOK_icon.svg",
    icon3: "assets/icons/PC_icon.svg",
    duracion: "9 a 12 meses",
    creditos: "20 ETC",
    modalidad: "Online"
  },
];


export default cardsData;